version: "3.9"

services:
  mysql:
    container_name: mysql-rick-and-morty
    image: mysql:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    ports:
      - "3306:3306"




